print("I’m planning to learn git conflicts resolution")
name = input("Please enter your name: ")
surname = input("Please enter your surname: ")
nickname = input("Please enter your nickname ")
print(f"Hi, {name} {surname} a.k.a {nickname}", format(name, surname))
